app:
  build-info:
    name: Hangman
    versionDate: ${buildDate:@buildDate@}
    url: ${ENV_VAR_WEB_APP_BASE_URL:@ENV_VAR_WEB_APP_BASE_URL@}

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            ## See also https://stackoverflow.com/a/50042533/704681
            clientId: ${ENV_VAR_CLIENT_ID_GITHUB:@ENV_VAR_CLIENT_ID_GITHUB@}
            clientSecret: ${ENV_VAR_CLIENT_SECRET_GITHUB:@ENV_VAR_CLIENT_SECRET_GITHUB@}
            redirectUri: ${ENV_VAR_WEB_APP_BASE_URL:@ENV_VAR_WEB_APP_BASE_URL@}/login/oauth2/code/github
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassname: org.h2.Driver
    username: amw
    password: amw
  jpa:
    show-sql: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web.client.RestTemplate: WARN
    org.springframework.web.filter.CommonsRequestLoggingFilter: WARN
    org.hibernate.validator.internal.engine.ValidatorImpl: WARN
    org.hibernate.type.descriptor.sql: WARN
    org.hibernate.SQL: INFO
    com.amwebexpert: INFO
