app:
  build-info:
    name: Hangman
    versionDate: 2021-03-21

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${ENV_VAR_CLIENT_ID_GITHUB:value_not_defined_in_environment_variable}
            clientSecret: ${ENV_VAR_CLIENT_SECRET_GITHUB:value_not_defined_in_environment_variable}
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassname: org.h2.Driver
    username: amw
    password: amw
  jpa:
    show-sql: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web.client.RestTemplate: WARN
    org.springframework.web.filter.CommonsRequestLoggingFilter: WARN
    org.hibernate.validator.internal.engine.ValidatorImpl: WARN
    org.hibernate.type.descriptor.sql: WARN
    org.hibernate.SQL: INFO
    com.amwebexpert: INFO
